* tattood-android
** Missing
  + Search Page (Works on clicking from tag/username but there is no dedicated search bar)
  + Upload (Tag, Privacy)
** Bug [3/7]
  + [X] See-More page shows empty entries
  + [ ] RecyclerView Creation is repeated way too many times
  + [X] tattoos should be saved using tattoo id not using loop index. (index might cause collision)
  + CameraFragment.java gives warning: attempt to use a camera after disconnect()
    Most probably onPause()/onResume() related
  + Visual Interface looks horrible
  + [ ] Recursive clicks should lead back to Discovery page (From tattoo? user? all?)
  + [X] Images should use fixed size
  + Login/Register requires a rework:
    + [X] Tokens change from time-to-time (maybe on uninstall). Server needs to adapt (Server code
      is updated to update token, but needs investigation, when/why token changes? or does it
      actually change?)
    + [X] Storing tokens in Server and checking it every time looks quite primitive (According to
      StackOverflow, using either this or ApplicationManager is the default way to go)
    + [ ] Server should use official Python API instead of HTTP request (Should, it?)
    + [X] If the user is already logged in, login activity should not appear
    + [X] Looks like some Firebase related operations are not performed during register
    + [X] Notifying un-registered user via 400 sounds like a poor design, (at least choose a
      different code) According to Wikipedia, for unauthorized access one should use 401. But this
      requires an authorization scheme. And I decided to go with 464, which is available to use
    + [X] Whether via back-button or something else, user should never be able to reach back the login screen
          :nohistory should fix this
  + Upload button does not appear in Profile Fragment
  + [ ] Change Upload button to FAB (will fix the above bug)
  + [ ] Change Camera button to FAB
  + Fix tattoo tags
    + [X] It should be a relation in the database instead of pipe separated lists
    + [X] Server must handle newly added tags
    + [ ] Currently, all requests to tattoo-update deletes all tags of a tattoo and reinserts. This,
      doesn't cause much problem since number of tags are quite small, but there might be a better
      way of doing this.
